### PR TITLE
fix(MembershipsSdkAdapter):added name property to member mapping in getmembers function

### PR DESCRIPTION
**Pull request by Parimala032**
## This pull request addresses 
This PR enhances the getMembers function by including the `name` property in the returned member objects. By adding the `name: member.name`, each member object now contains the participant's display name in a local sample app of widgets, improving the comprehensiveness of the member data. If the user wanted to pass the `name` according to there wish that will be appear on widgets sample app (or) the system default name will be displayed

please do refer to the screenrecording

https://github.com/user-attachments/assets/5cc7464e-bbc4-470c-a44b-f61e96e93e79

## Summary by CodeRabbit

- **New Features**
	- Enhanced member information by including the member's name in the list returned by the membership function.
  
- **Bug Fixes**
	- Improved error handling for invalid meeting IDs and SDK failures in adding members.

- **Tests**
	- Expanded test coverage for member attributes and refined error handling in the membership-related tests.

### CODE REVIEW

**Review by adhmenon — APPROVED** [review]
LGTM. Noticed you have added check in the other repo.

**Review by rsarika — APPROVED** [review]

**Comment by Parimala032** [comment]
> LGTM. Noticed you have added check in the other repo.

Yes @adhmenon the check for this is there in the components repo because this function will return the members object that the members object call actually has been there in the components repo so here we just include the name as a property in the members function previously it was not there if we include this property then only the user accepting wished name will be visible on widgets sample app

**Comment by Parimala032** [comment]
@adhmenon  for you question What happens if this value comes as undefined? Do we have an edge check? below is the answer

The current statement has an implicit edge check due to the use of optional chaining and the || operator. It will handle cases where  member.name is undefined by falling back to displayName.

**Pull request merged**
