### PR TITLE
fix(package): set webex packages to 1.80.43

### PR DESCRIPTION
**Pull request by adamweeks**

### CODE REVIEW

**Comment by adamweeks** [comment]
@akoushke dismissed your review because it was using the latest version of the sdk, but that appears to be problematic, so setting the version to the current version. 

@lalli-flores we should create a JIRA for updating to the very latest version of the sdk, but it will be more work due to some service catalog issues.

**Comment by akoushke** [comment]
so the aphelia service works here?

**Comment by adamweeks** [comment]
@akoushke 

> so the aphelia service works here?

yes, works fine after sticking the version.

**Pull request merged**
